[[spring-component:Default]]
[role=group,includesConstraints="spring-component:ControllerDependencies,spring-component:ControllerMustBeLocatedInWebLayer,spring-component:ServiceDependencies,spring-component:ServiceMustBeLocatedInServiceLayer,spring-component:RepositoryDependencies,spring-component:RepositoryMustBeLocatedInRepositoryLayer,spring-component:ImplementationDependencies,dependency:PackageCycles",includesConcepts="spring-component:ComponentDependencies.graphml"]
== Spring Components

The following constraints are verified:

- <<spring-component:ControllerDependencies>>
- <<spring-component:ControllerMustBeLocatedInWebLayer>>
- <<spring-component:ServiceDependencies>>
- <<spring-component:ServiceMustBeLocatedInServiceLayer>>
- <<spring-component:RepositoryDependencies>>
- <<spring-component:RepositoryMustBeLocatedInRepositoryLayer>>
- <<spring-component:ImplementationDependencies>>
- Package cycles

The following GraphML reports are created:

- <<spring-component:ComponentDependencies.graphml>>

=== Overview

The application consists of the following components:

[plantuml,class-diagram]
....
package UI <<Frame>> {
  class MyController
}

package Logic <<Frame>> {
  interface MyService
  MyService <|-- MyServiceImpl
}

package Persistence <<Frame>> {
  interface FooRepository
  interface SpringDataFooRepository
  FooRepository <|-- SpringDataFooRepository
  FooRepository <|-- JpaFooRepositoryImpl
  FooRepository <|-- JdbcFooRepositoryImpl
}

MyController --> MyService : uses
MyServiceImpl --> FooRepository : uses

hide members
....

* UI
** Controller implementations
* Logic
** Service interfaces and implementations
* Persistence
** Repository interfaces and implementations
*** Spring Data (interface declaration only)
*** JPA
*** JDBC

=== Constraints

The following sections describe restrictions on dependencies between these components.

==== General

[[spring-component:ImplementationDependencies]]
[source,cypher,role=constraint,requiresConcepts="spring-mvc:Controller,spring-mvc:Service,spring-data:Repository"]
.There must be no direct dependencies between Spring component implementations, i.e. only dependencies to interfaces are allowed.
----
MATCH
  (type:Spring:Component)-[:DECLARES]->(:Method)-[:INVOKES]->(:Method)<-[:DECLARES]-(otherType:Spring:Component)
WHERE
  type <> otherType
  and not otherType:Interface
RETURN DISTINCT
  type as Dependent, otherType as InvalidDependency
----

==== UI

The server side UI implementation is based on Spring MVC controllers:

[source,java]
.Example controller
----
@Controller
@RequestMapping("/resource")
public class MyController {

    private final MyService service;

    @Autowired
    public MyController(MyService myService) {
        this.myService = myService;
    }

    @RequestMapping(value = "/", method = RequestMethod.GET)
    public String get() {
    }
}
----

[[spring-component:ControllerDependencies]]
[source,cypher,role=constraint,requiresConcepts="spring-component:ComponentDependencies"]
.A controller can only have dependencies to services (e.g. direct usage of repositories is not allowed).
----
MATCH
  (type:Spring:Controller)-[:USES]->(otherType:Spring:Component)
WHERE NOT
  otherType:Service
RETURN DISTINCT
  type as InvalidController, otherType as Dependency
----

[[spring-component:ControllerMustBeLocatedInWebLayer]]
[source,cypher,role=constraint,requiresConcepts="spring-component:Component,package:Layer"]
.A controller must be located in the layer named 'web'.
----
MATCH
  (controller:Spring:Controller)
WHERE NOT
  (:Layer{name:"web"})-[:CONTAINS*]->(controller)
RETURN
  controller as Controller
----

==== Logic

The business logic consists of services which are defined by interfaces and implemented by classes annotated with @Service:

[source,java]
.Example service interface
----
public interface MyService {
    Collection<Foo> findFoos() throws DataAccessException;
}
----

[source,java]
.Example service implementation
----
@Service
public class MyServiceImpl implements MyService {

    private FooRepository fooRepository;

    @Autowired
    public ServiceImpl(FooRepository fooRepository) {
        this.fooRepository = fooRepository;
    }
}
----

[[spring-component:ServiceDependencies]]
[source,cypher,role=constraint,requiresConcepts="spring-component:ComponentDependencies"]
.A service can only have dependencies to repositories or other services (e.g. usage of controllers is not allowed).
----
MATCH
  (type:Spring:Service)-[:USES]->(otherType:Spring:Component)
WHERE NOT (
  otherType:Service
  or otherType:Repository
)
RETURN DISTINCT
  type as InvalidService, otherType as Dependency
----

[[spring-component:ServiceMustBeLocatedInServiceLayer]]
[source,cypher,role=constraint,requiresConcepts="spring-component:Component,package:Layer"]
.A service must be located in the layer named 'service'.
----
MATCH
  (service:Spring:Service)
WHERE NOT
  (:Layer{name:"service"})-[:CONTAINS*]->(service)
RETURN
  service as Service
----

==== Persistence

Repositories provide access to the database and are defined by interfaces (one per model element):

[source,java]
.Example repository interface
----
public interface FooRepository {
    Collection<Foo> findFoos() throws DataAccessException;
}
----

There are three options to provide or implement a repository:

[source,java]
.Example Spring Data repository
----
public interface SpringDataFooRepository extends FooRepository, Repository<Foo, Integer> {

    @Override
    @Query("SELECT foo FROM Foo ORDER BY foo.name")
    List<Foo> findFoos() throws DataAccessException;
}
----

[source,java]
.Example JPA repository
----
@Repository
public class JpaFooRepositoryImpl implements FooRepository {

    @PersistenceContext
    private EntityManager em;

    @Override
    @SuppressWarnings("unchecked")
    public List<Foo> findFoos() {
        return this.em.createQuery("SELECT foo FROM Foo ORDER BY foo.name").getResultList();
    }
----

[source,java]
.Example JDBC repository
----
@Repository
public class JdbcFooRepositoryImpl implements Repository {

    private NamedParameterJdbcTemplate namedParameterJdbcTemplate;

    @Autowired
    public JdbcRepositoryImpl(DataSource dataSource) {
        this.namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(dataSource);
    }

    @Override
    public List<Foo> findFoos() throws DataAccessException {
        Map<String, Object> params = new HashMap<>();
        return this.namedParameterJdbcTemplate.query(
            "SELECT id, name FROM foo ORDER BY name",
            params,
            BeanPropertyRowMapper.newInstance(Foo.class));
    }
----

[[spring-component:RepositoryDependencies]]
[source,cypher,role=constraint,requiresConcepts="spring-component:ComponentDependencies"]
.A repository can only have dependencies to other repositories.
----
MATCH
  (type:Spring:Repository)-[:USES]->(otherType:Spring:Component)
WHERE NOT
  otherType:Repository
RETURN DISTINCT
  type as InvalidRepository, otherType as Dependency
----

[[spring-component:RepositoryMustBeLocatedInRepositoryLayer]]
[source,cypher,role=constraint,requiresConcepts="spring-component:Component,package:Layer"]
.A repository must be located in the layer named 'repository'.
----
MATCH
  (repository:Spring:Repository)
WHERE NOT
  (:Layer{name:"repository"})-[:CONTAINS*]->(repository)
RETURN
  repository as Repository
----


=== Concepts

[[spring-component:Component]]
[source,cypher,role=concept,requiresConcepts="spring-mvc:Controller,spring-mvc:Service,spring-data:Repository"]
.Reports all Spring components.
----
MATCH
  (component:Spring:Component)
RETURN
  component as Component
----

[[spring-component:ComponentDependencies]]
[source,cypher,role=concept,requiresConcepts="spring-component:Component"]
.Creates a USES relation between Spring components.
----
MATCH
  (type:Spring:Component)-[:DECLARES]->(:Method)-[:INVOKES]->(:Method)<-[:DECLARES]-(:Type:Interface)<-[:IMPLEMENTS|EXTENDS*]-(otherType:Spring:Component)
WHERE
  type <> otherType
MERGE
  (type)-[:USES]->(otherType)
RETURN
  type as Dependent, collect(distinct otherType.fqn) as Dependencies
----

=== Reports

[[spring-component:ComponentDependencies.graphml]]
[source,cypher,role=concept,requiresConcepts="spring-component:ComponentDependencies",reportType="graphml"]
.Actual usage dependencies between Spring components, i.e. controller, service and repository implementations.
----
MATCH
  (type:Spring:Component)-[uses:USES]->(otherType:Spring:Component)
RETURN
  type as Dependent,
  uses as Uses,
  otherType as Dependency
----

